---
os: osx
language: objective-c
# command to install dependencies
before_install:
  - brew install python
  - brew install lame
  - brew install ffmpeg --with-fdk-aac
  - brew install derphilipp/homebrew-sublercli/sublercli --HEAD
  - brew cask install kid3
install:
  - pip install -r requirements.txt
  - pip install flake8
# command to run tests
script:
  - pytest tests
  - flake8 .
