---
os: osx
osx_image: xcode9.2
language: objective-c
# command to install dependencies
before_install:
  - brew install python
  - brew install lame
  - brew install ffmpeg --with-fdk-aac
  - brew install mp4box
  - brew cask install kid3
install:
  - pip install -r requirements.txt
  - pip install flake8
# command to run tests
script:
  - pytest tests
  - flake8 .
