---
language: python

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      python: 3.7
    - os: osx
      osx_image: xcode11.3
      language: generic

addons:
  apt:
    packages:
      - lame
      - gpac
      - kid3-cli


# command to install dependencies

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -q; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install ffmpeg -y; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew-ffmpeg/ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python3; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install lame; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install mp4box; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew cask install kid3; fi

install:
  - pip3 install poetry
  - poetry install
# command to run tests
script:
  - poetry
  - poetry run pytest
  #- pytest tests
  #- flake8 .
